log_dir = "log"
info_dir = 'info'
websocket_host = "0.0.0.0"
websocket_port = 8765
api_key = 'sk-3NDFbHCTHJJSTrXEB8A5A489A7Ec44D1B7A9A51d2bE34aDd'
base_url = 'https://api.vveai.com/v1/'
model_name = 'o4-mini'

[suffix]
chat = '请输入(有/没有)'
exam = '请按以下格式回答：(1.xx 2.xx 3.xx)'
name = '请直接输入姓名'